name: Update Version Info

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Version Info
        run: |
          # Set timezone to EST for date command
          export TZ="America/New_York"
          
          # Format date with EST time (12-hour format with AM/PM)
          BUILD_DATETIME=$(date '+%Y-%m-%d %I:%M %p EST')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          
          # Use the commit hash as part of the version
          echo "window.SITE_VERSION = {" > version.js
          echo "  version: \"${COMMIT_HASH}\"," >> version.js
          echo "  buildDate: \"$BUILD_DATETIME\"" >> version.js
          echo "};" >> version.js
          
          # Debug - show the content
          echo "Generated version.js:"
          cat version.js

      - name: Commit Version File
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add version.js
          git commit -m "Update version info" || echo "No changes to commit"
          git push