name: Update Version Info

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Version Info
        run: |
          BUILD_DATE=$(date '+%Y-%m-%d')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "window.SITE_VERSION = {" > version.js
          echo "  version: \"1.0.0\"," >> version.js
          echo "  buildDate: \"$BUILD_DATE\"," >> version.js
          echo "  commit: \"$COMMIT_HASH\"" >> version.js
          echo "};" >> version.js
          
          # Debug - list files
          echo "Files in directory after generating version.js:"
          ls -la

      # Remove the Deploy step that uses JamesIves action
      # Instead, commit changes directly to main branch
      - name: Commit Version File
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add version.js
          git commit -m "Update version info" || echo "No changes to commit"
          git push
